[[plugins]]
package = "netlify-plugin-imageengine"

  [plugins.inputs]
  deliveryAddress = "blazing-fast-pics.cdn.imgeng.in"

  [plugins.inputs.directives]
  height = 600
  width = 700
  rotate = 90

[build]
publish = "./"

[build.environment]
NODE_VERSION = "18"